#!/bin/sh
#
# git-tagger.sh
#
# automatically add a tag to the given git repositories
# input: a list of target git repositories that is generated by meta-debian
#
# (example)
# input: git.list.git.server.com,
# usage: ./git-tagger.sh git.list.git.server.com git.server.com tagname
#

WORKDIR=$(pwd)
LIST=$WORKDIR/tag.list
LOG=$WORKDIR/git-tagger.log
CLONEDIR=${WORKDIR}/git

usage() {
	echo "
usage: $0 <git.list> <server> <tag> [-s|-d]

arguments:
    git.list : a list of git repositories generated by meta-debian
    server   : the git server name that provides all repositories in git.list
    tag      : net tag name

options:
    -s : no push, just confirm that <tag> can be added to all repositories
    -d : delete mode; delete given tag in all repositories

example:
    $0 git.list.git.server.com git.server.com tagname
"
	exit 2
}

die() {
	echo "ERROR: $@"
	exit 1
}

# arguments
REPOINFO="$1"
SERVER="$2"
TAG="$3"
[ -n "$TAG" ] || usage
[ -f $REPOINFO ] || die $REPOINFO not found

# options
OPT="$4"

cat $REPOINFO | sort | uniq > $LIST

# confirm LIST
echo "confirming $REPOINFO..."
while read line; do
	! echo "$line" | grep -q "^#" || continue
	path=$(echo "$line" | cut -d " " -f 1)
	commit=$(echo "$line" | cut -d " " -f 2)
	[ -n "$path" -a -n "$commit" ] || die "invalid line: $line"
	uri=git://$SERVER/$path
	echo "$uri"

	git ls-remote $uri > /dev/null 2>&1 || \
		die "cannot access to $uri"

	if [ "$OPT" = "-d" ]; then
		[ -n "$(git ls-remote --tags $uri $TAG)" ] || \
			die "tag $TAG not found in $uri"
	else
		git ls-remote $uri | sed "s@\s.*@@" | grep -q "^$commit$" || \
			die "commit $commit not found in $uri"
		[ -z "$(git ls-remote --tags $uri $TAG)" ] || \
			die "tag $TAG is already defined in $uri"
	fi
done < $LIST
printf "done\n\n"

if [ "$OPT" = "-s" ]; then
	rm -f $LIST
	echo "Tag \"$TAG\" can be added to all repositories."
	echo "This is just a simulation, exiting without push to them..."
	exit 0
fi

# tagging
rm -rf $LOG $CLONEDIR
if [ "$OPT" = "-d" ]; then
	echo "deleting tag \"$TAG\" in each repository..."
else
	echo "adding tag \"$TAG\" to each repository..."
fi
while read line; do
	path=$(echo "$line" | cut -d " " -f 1)
	commit=$(echo "$line" | cut -d " " -f 2)
	uri=git://$SERVER/$path
#	uri=gitosis@$SERVER:$path

	if [ "$OPT" = "-d" ]; then
		echo "deleting $TAG in $uri" | tee -a $LOG
	else
		echo "$TAG => $uri $commit" | tee -a $LOG
	fi

	# clone
	echo "git clone --bare $uri $CLONEDIR" >> $LOG
	git clone --bare $uri $CLONEDIR >> $LOG 2>&1 || die "git clone failed"

	cd $CLONEDIR
	if [ "$OPT" = "-d" ]; then
		# delete tag
		echo "git push origin :refs/tags/$TAG" >> $LOG
		git push origin :refs/tags/$TAG >> $LOG 2>&1 || die "failed to delete tag"
	else
		# add a tag
		echo "git tag $TAG $commit" >> $LOG
		git tag $TAG $commit >> $LOG 2>&1 || die "git tag failed"
		# push
		echo "git push --tags" >> $LOG
		git push --tags >> $LOG 2>&1 || die "git push failed"
	fi
	cd $WORKDIR

	echo "----------------------------------------------------------------------" >> $LOG
	rm -rf $CLONEDIR
done < $LIST

rm -f $LIST
echo "done"
